use list::make_tuple_helpers;


make_tuple_helpers!(  0, unit);
make_tuple_helpers!(  1, monuple);
make_tuple_helpers!(  2, couple);
make_tuple_helpers!(  3, triple);
make_tuple_helpers!(  4, quadruple);
make_tuple_helpers!(  5, quintuple);
make_tuple_helpers!(  6, sextuple);
make_tuple_helpers!(  7, septuple);
// make_tuple_helpers!(  8, octuple);
// make_tuple_helpers!(  9, nonuple);
// make_tuple_helpers!( 10, decuple);
// make_tuple_helpers!( 11, undecuple);
// make_tuple_helpers!( 12, duodecuple);
// make_tuple_helpers!( 13, tredecuple);
// make_tuple_helpers!( 14, quattuordecuple);
// make_tuple_helpers!( 15, quindecuple);
// make_tuple_helpers!( 16, sexdecuple);
// make_tuple_helpers!( 17, septendecuple);
// make_tuple_helpers!( 18, octodecuple);
// make_tuple_helpers!( 19, novemdecuple);
// make_tuple_helpers!( 20, vigintuple);
// make_tuple_helpers!( 21, unvigintuple);
// make_tuple_helpers!( 22, duovigintuple);
// make_tuple_helpers!( 23, trevigintuple);
// make_tuple_helpers!( 24, quattuorvigintuple);
// make_tuple_helpers!( 25, quinvigintuple);
// make_tuple_helpers!( 26, sexvigintuple);
// make_tuple_helpers!( 27, septenvigintuple);
// make_tuple_helpers!( 28, octovigintuple);
// make_tuple_helpers!( 29, novemvigintuple);
// make_tuple_helpers!( 30, trigintuple);
// make_tuple_helpers!( 31, untrigintuple);
// make_tuple_helpers!( 40, quadragintuple);
// make_tuple_helpers!( 41, unquadragintuple);
// make_tuple_helpers!( 50, quinquagintuple);
// make_tuple_helpers!( 60, sexagintuple);
// make_tuple_helpers!( 70, septuagintuple);
// make_tuple_helpers!( 80, octogintuple);
// make_tuple_helpers!( 90, nongentuple);
// make_tuple_helpers!(100, centuple);